Fix drop shadow issue in Safari for menu and filter
Shopify/dawn pull request #1212
Opened 2022-01-18 21:21 UTC by ludoboludo

**Why are these changes introduced?**

Fixes #1213 issue with drop shadow on the menu dropdown and filter in Safari: [video](https://screenshot.click/22-01-732uy-lcn0h.mp4)

**What approach did you take?**

On predictive search, the `transform` approach work but not on the dropdown/popup of the filter and header menu.

**Other considerations**

Not super stoked to use will-change like this as it's meant to be used sparingly
Could also take a bit more time and see if it'd be worth tackling those box shadows with pseudo elements like in other part of the theme. 

**Testing**

To test you can follow the steps in the video shared above. Basically:
- add shadow on popups and check in Safari to make sure there isn't anything weird happening on : 
    - predictive search
    - filter drop down
    - and menu popup/dropdown

**Demo links**

- [Store](https://os2-demo.myshopify.com/?preview_theme_id=127455035414)
- [Editor](https://os2-demo.myshopify.com/admin/themes/127455035414/editor)

**Checklist**
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2022-01-24 19:30 UTC, ludoboludo commented
I think it might take a bit of work to try and see if it could work as an pseudo element styling with `:after`. Since `facets__display` is set to position absolute already.

2022-01-24 20:09 UTC, kmeleta reviewed
I don't have any problem with these fixes, but it's possible we can avoid the issue by using box-shadow instead of filter for all these cases. Safari might just be trying too hard to optimize the filter or something 🤷

2022-01-24 21:35 UTC, kmeleta reviewed
I think I found this happening in the locale select as well, could we see if it's safe to address here too while we're at it? 
<img src="https://screenshot.click/24-34-zs9ve-ogiz6.png" width="400"/>

2022-01-24 21:51 UTC, martinamarien commented
> could we see if it's safe to address here too while we're at it?

I didn't see your comment, Ken. I agree we should so it here. It's definitely safe. The class is only being used for these selectors.

2022-01-24 22:37 UTC, kmeleta submitted a review, later dismissed
LGTM 👍

2022-01-24 23:03 UTC, martinamarien approved these changes
Looks good to me 👍🏻 
Thanks for adding the `disclosure` update

2022-01-24 23:06 UTC, martinamarien requested changes
Sorry. I found one more. 
Not that I found an issue with it in Safari, but if we are updating all popups/dropdowns to use `box-shadow`, then we should also update `.cart-notification`. It's still using Filter.

2022-01-25 15:04 UTC, ludoboludo commented on assets/component-predictive-search.css
>  }
yeah this is for the predictive one. The drop down that shows when you start typing something in the search bar.

2022-01-25 15:20 UTC, ludoboludo commented
So for both the cart notification and the popup on the product page, it doesn't work exactly the same. As both of those containers receive focus unlike the other element touched so far. 
If cart wasn't having an issue, I'd rather keep with the `filter: drop-shadow()` approach. Check out this [video](https://screenshot.click/22-01-cvsih-mf9zk.mp4). 

As for the popup on the product page, the box shadow styling takes precedence over the `box-shadow` being received when it's open and the container focused (with the .focused class). [Video](https://screenshot.click/22-01-003xb-rymq8.mp4). Are we ok with changing it there then ? 

Again I think i'd keep `filter` for the cart notification as it didn't seem to be an issue in the first place. As for the popup on the product page, I could keep the `filter` and add `will-change: filter;` to it and solve the issue while keeping the intended focus state.

2022-01-25 17:03 UTC, martinamarien submitted a review, later dismissed

2022-01-25 17:50 UTC, martinamarien commented on assets/section-main-product.css
> +  var(--popup-shadow-horizontal-offset) var(--popup-shadow-vertical-offset) var(--popup-shadow-blur-radius) rgba(var(--color-shadow), var(--popup-shadow-opacity));
I'm okay with this. 
But we will also need to modify the `:focus-visible` focus state. It's not showing the right box-shadow when focused now. The 0.3rem "background" border is missing. I think.

Expectation: 
<img width="982" alt="Screen Shot 2022-01-25 at 12 49 23 PM" src="https://user-images.githubusercontent.com/26778637/151031352-c007f5ba-772d-4ca2-afbf-5137871e6a83.png">

New focus experience: 
<img width="1009" alt="Screen Shot 2022-01-25 at 12 49 49 PM" src="https://user-images.githubusercontent.com/26778637/151031412-43c430ef-1d17-4217-b9ab-b82b94c8799b.png">

2022-01-25 18:50 UTC, martinamarien approved these changes
Looks good Ludo. 

Tested 
- [x] Safari, Chrome, Firefox 
- [x] Predictive search, product popup block, cart notification, menu dropdowns, filters, currency/language selectors.

2022-01-25 19:27 UTC, kmeleta approved these changes
Tested all applicable sections in chrome/safari. Noticed no regressions in focus behavior. :shipit:

2022-01-25 19:28 UTC, merged