Cleanup product media grid spacing
Shopify/dawn pull request #1444
Opened 2022-03-03 16:29 UTC by kmeleta

**PR Summary:** 

Fixes some minor spacing inconsistencies in the product media gallery noticeable on tablet viewports.

**Why are these changes introduced?**

Some of these spacing/grid updates need to be resolved for future 0 spacing grid changes, but I'm also cleaning up a couple other visual bugs I noticed.

Product media gallery spacing issues at the tablet breakpoint:
<details>
<summary>Incorrect vertical grid spacing</summary>
<img src="https://screenshot.click/02-49-s2ldl-n4n6s.png" width="300"/>
</details>
<details>
<summary>Thumbnails misaligned</summary>
<img src="https://screenshot.click/02-46-g8hv3-ltloh.png" width="300"/>
</details>
<details>
<summary>Thumbnails not horizontally centered in carousel</summary>
<img src="https://screenshot.click/02-50-6485k-sz23a.png" width="300"/>
</details>

Product media grid not behaving like other grids:
<details>
<summary>Last item is always fullwidth</summary>
<img src="https://screenshot.click/03-13-5ool8-7npsg.png" width="300"/>
</details>

**What approach did you take?**

I choose to make the needed grid changes without introducing any new grid--#-col type classes on the product media grid. This would have consequences for upcoming grid collapse work. I also feel there could be some future opportunity for consolidation with the main blog grid, which is also an "irregular" 2-col grid.

**Other considerations**

**Testing steps/scenarios**

View product media gallery in all layout modes at all viewport sizes. Ensure there are no regressions other than the changes notes above.

**Demo links**

[Product with odd number of gallery items](https://os2-demo.myshopify.com/admin/themes/127670714390/editor?previewPath=%2Fproducts%2Fcopy-of-naomi-mini-wallet-st-tropez)
[Product with even number of gallery items](https://os2-demo.myshopify.com/admin/themes/127670714390/editor?previewPath=%2Fproducts%2Fbo-ivy-cognac%3Fpr_prod_strat%3Dcollection_fallback%26pr_rec_id%3D7bde49e17%26pr_rec_pid%3D6566158762006%26pr_ref_pid%3D6568788394006%26pr_seq%3Duniform)
[Product with deferred media](https://os2-demo.myshopify.com/admin/themes/127670714390/editor?previewPath=%2Fproducts%2Ftest-3d-models-video)

**Checklist**
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2022-03-04 19:41 UTC, ludoboludo submitted a review, later dismissed
Looks good 👌 

I had some general feedback while testing this: 
- when to show apply the `slider__slide` class for thumbnails: [video](https://screenshot.click/04-14-nmakx-fcg74.mp4)
- the width of images when set to small `desktop media size`: [video](https://screenshot.click/04-35-9xgjq-rkyj9.mp4)

2022-03-04 23:40 UTC, kmeleta commented
> * the width of images when set to small `desktop media size`: [video](https://screenshot.click/04-35-9xgjq-rkyj9.mp4)

Honestly I just recently learned the media _doesn't_ go to fullwidth when there's deferred media.. so I could be sold either way here.  I will say though, when viewing a product with a large amount of videos and things like our test product, it can seem odd the few images still default to 2 columns, but I think given the more typical case of mostly images with perhaps 1 video or model, this logic makes more sense.

The one problem I have with it though, is if you have a video, then 1 image, then video, that image is kind of made an orphan because it has no second image to to split the column with. @ludoboludo

2022-03-07 16:43 UTC, YoannJailin commented
@kmeleta okay got it. I still see the misalignement but let's keep it for the other ticket then. ;)

2022-03-07 16:43 UTC, YoannJailin approved these changes

2022-03-08 15:15 UTC, martinamarien requested changes
Looking pretty good Ken. I just noticed one issue for the slider on desktop, as a result of the styling you applied for product media items.

2022-03-08 16:43 UTC, merged