[Collection template] Product grid color scheme picker
Shopify/dawn pull request #3017
Opened 2023-09-27 22:00 UTC by ludoboludo

### PR Summary: 

Add color scheme picker to the product grid section of the Collection template page

### Why are these changes introduced?

Adding more flexibility to the collection page. You can already change the collection banner color scheme so it makes sense to have the option for the product grid as well.

### What approach did you take?
Added class on the wrapping element as well as the setting

### Visual impact on existing themes

Adds the option to pick a color scheme for the product grid part of the collection template.
? The filter drawer is inheriting the color scheme applied to this section. Not sure if it's something we're wanting or if we should prevent it. 
? The quick add modal isn't using the color scheme picked in that section. Should it ? Or where should that modal color be set ? [screenshot](https://screenshot.click/27-02-r168x-u1w6c.png)

### Testing steps/scenarios

- [ ] Go to a collection page
- [ ] Change the color scheme for the `product grid` section
- [ ] Check and confirm it's behaving as expected. Filters are working, quick add is working, no icons or text is hidden

### Demo links

- [Editor](https://admin.shopify.com/store/os2-demo/themes/157723721750/editor)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2023-10-16 15:14 UTC, sofiamatulis approved these changes
Works well 🎉 

I think itll be important to re-test this with this new feature: https://github.com/Shopify/dawn/pull/3045

2023-10-19 02:00 UTC, melissaperreault requested changes
I would recommend to move the Color scheme setting at the top under the Product grid heading, below the 2 range settings. cc. @katycobb For visibility, the color scheme is applied entirely not only on product cards which it's positioned right now. Thoughts?

Any concern on moving it?

2023-10-19 14:49 UTC, melissaperreault commented
Oops just tested agains [a gradient background](https://screenshot.click/19-48-bspxz-cakgf.png), I think we would nee to support it 🙏

2023-10-20 17:14 UTC, melissaperreault commented
> It looks a little funny when you're applying filters and it reload the product cards. But I don't think it's blocking.

Yeah, you are right! It's a little weird but exists on main. We can open a new issue to follow up on that someday!

2023-10-20 17:33 UTC, eugenekasimov approved these changes
Works as expected 🚀

I leave my two cents though, I don't like the filter drawer inherits color scheme from grid template but it's not call I guess 🤪

2023-10-20 18:22 UTC, merged