[Cart] Add color picker on cart page and in general cart settings
Shopify/dawn pull request #3021
Opened 2023-09-29 15:44 UTC by ludoboludo

### PR Summary: 

Adds the color picker to both the cart items section and cart subtotal section.
Add the color picker to the general settings which will apply to the cart popup notification and the cart drawer

### Why are these changes introduced?

We're wanting to provide more customizability with color schemes. 

### What approach did you take?

### Other considerations
I'm not sure we should be applying the color scheme from the cart settings to the popup notification as it used to match the color scheme used by the header section. Curious to know what reviewers think about that. 

### Visual impact on existing themes

Cart popup notification is now not following the color scheme of the header. 

### Testing steps/scenarios

- [ ] Go to the cart page while it's empty and change the color scheme
- [ ] Go to the cart page when items are added in there and change the color theme
- [ ] Make sure discounts, text, buttons are coming up in the right color and visible. 
- [ ] Go to general cart settings and change the cart type and color scheme
- [ ] Make sure it applies in all states of the cart as expected

### Demo links

- [Editor](https://admin.shopify.com/store/os2-demo/themes/157736042518/editor)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2023-09-29 15:45 UTC, ludoboludo commented
@danielvan we could move the color picker at the theme settings level so that the color scheme picked is applied to both the cart drawer and the cart page 🤔 But it wouldn't apply to the cart popup. 

What do you think ?

2023-10-09 10:30 UTC, danielvan commented
@katycobb for the content, do you think we can rename "Pop up notification" to "Pop up"? It would look nicer in the segmented control.

2023-10-10 15:18 UTC, ludoboludo commented
Waiting on having some more feedback on this to decide where it should be living (the color picker setting), in the general settings for cart or on the cart page. And also if we want the same pattern applied to the popup notification and cart drawer.

2023-10-16 16:09 UTC, kmeleta commented on config/settings_schema.json
> +      },
If we do keep it this way, adding some helper text that clarifies the scope of this setting and/or where the cart page color scheme can be configured might be useful.

2023-10-16 16:22 UTC, ludoboludo commented on sections/header.liquid
> +  {%- render 'cart-notification', desktop_menu_type: section.settings.menu_type_desktop -%}
I agree with that take. I think it makes sense for it to inherit the color scheme of the header.

2023-10-17 14:37 UTC, melissaperreault commented
Noting my observations here even though some of them were already soled for for documentation:

- [x] Changing top padding from 0 to 4px on the Items section is unexpected
- [x] Another example where the padding and result is odd ([Video](https://screenshot.click/13-30-jvsi9-lyuyg.mp4))

**Not a blocker for this PR**
I'll open issues for those ones soon.
- [ ] Cart note expandable drag goes beyond its section
- [ ] Layout spacing between sections don’t get applied between cart sections and the subsequent section right after it

2023-10-17 16:28 UTC, eugenekasimov commented on sections/header.liquid
> +  {%- render 'cart-notification', desktop_menu_type: section.settings.menu_type_desktop -%}
+1

2023-10-17 16:37 UTC, eugenekasimov commented on config/settings_schema.json
> +      },
> * The cart items and footer sections haven't historically had useful settings so a user may not naturally think to look in there for further style options.

I have the same thought on it, but it's definitely not a blocker.

2023-10-18 19:18 UTC, eugenekasimov approved these changes
Looks good to me 👍

2023-10-19 15:58 UTC, ludoboludo commented on snippets/cart-drawer.liquid
> +<cart-drawer class="drawer gradient color-{{ settings.cart_color_scheme }}{% if cart == empty %} is-empty{% endif %}">
good catch 👌 Thank you!

2023-10-19 18:01 UTC, ludoboludo commented on assets/component-cart-drawer.css
> -  background-color: rgb(var(--color-background));
I'd hope so due to the name of the CSS asset 😅

2023-10-20 17:03 UTC, melissaperreault requested changes
- [x] Small regression, we lost the shadow applied on the Input component. ([Video reference](https://screenshot.click/20-02-tmqxt-jihsh.mp4))

2023-10-23 18:16 UTC, merged