Update README.md
Shopify/dawn pull request #3128
Opened 2023-11-24 14:53 UTC by benjaminsehl

Quickstart guide for devs is outdated, updating to link in shopify.dev

2023-11-24 16:24 UTC, charlespwd approved these changes

2024-02-07 19:16 UTC, ludoboludo requested changes

2024-02-07 19:16 UTC, ludoboludo commented on README.md
> +You can follow this [quick start guide for theme developers]([https://github.com/Shopify/shopify-cli#quick-start-guide-for-theme-developers](https://shopify.dev/docs/themes/tools/cli)) to get started
```suggestion
You can follow this [quick start guide for theme developers](https://shopify.dev/docs/themes/tools/cli) to get started.
```

2024-02-07 19:18 UTC, ludoboludo approved these changes

2024-02-07 19:21 UTC, merged