[WIP]
Shopify/dawn pull request #3289
Opened 2024-02-21 14:15 UTC by lhoffbeck

### PR Summary: 

### Why are these changes introduced?

Fixes #0.

### What approach did you take?

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

### Testing steps/scenarios

- [ ] Step 1

### Demo links

- [Store](url)
- [Editor](url)

### Checklist
- [ ] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [ ] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [ ] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [ ] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [ ] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [ ] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2024-02-22 20:57 UTC, lhoffbeck commented on assets/global.js
This is the primary change of this PR--extracting product-update logic out of VariantSelects to a wrapper class. This also enables us to eliminate some gnarly selectors from [here](https://github.com/Shopify/dawn/pull/3289/files#diff-47a8b2f1172e03da15783b379f0e007d8e3dfd27cbd9142adf9e32c4b9591079L1152-L1158) and [here](https://github.com/Shopify/dawn/pull/3289/files#diff-47a8b2f1172e03da15783b379f0e007d8e3dfd27cbd9142adf9e32c4b9591079L1170-L1172).

2024-02-22 21:23 UTC, lhoffbeck commented on assets/product-info.js
> -        this.submitButton = this.querySelector('[type="submit"]');
`currentVariant` can be grabbed from the product form class, `submitButton` wasn't used anywhere.

2024-02-23 16:14 UTC, lhoffbeck commented on assets/quick-order-list.js
This content update now happens declaratively in ProductInfo

2024-02-23 16:15 UTC, lhoffbeck commented on assets/global.js
>    connectedCallback() {
Recommendation reinitialization now happens declaratively in the ProductInfo class

2024-03-19 15:10 UTC, tauthomas01 reviewed
There are a few things I noticed while tophatting:

1) When I use tab navigation, navigating through options with regular variant switching works well (e.g. `?variant=47651697099054`), but when I load new child product (e.g. `chinos-black?variant=xxx`), the focus is set after the main product section. Since it's loaded asynchronously, it would be nice to set the focus before the main product section so we're not losing out sight when a new content is loaded.

https://github.com/Shopify/dawn/assets/658169/fa56a1a9-c29c-4566-9557-7813f38b4c09

2) There is a JS error in some case where the cart section id looks undefined when adding the product into the cart. It says the following:

```
TypeError: Cannot read properties of null (reading 'innerHTML')
    at CartNotification.getSectionInnerHTML(cart-notification.js:66:85)
```

I looked into this and it's related to this:

```
getSectionInnerHTML(html, selector = '.shopify-section') {
    return new DOMParser().parseFromString(html, 'text/html').querySelector(selector).innerHTML;
  }
```

Printing the `selector` param returns this: `'[id="cart-notification-product-undefined"]'`

https://github.com/Shopify/dawn/assets/658169/0ad053a0-610c-4154-80c7-b415e5f6b50e

2024-05-23 19:21 UTC, lhoffbeck commented on assets/product-form.js
> +      }
`toggleSubmitButton` logic was pulled out of the VariantSelects class

2024-05-23 19:28 UTC, lhoffbeck commented on sections/main-product.liquid
>  >
Worth flagging, this node was changed from a `section` to a `product-info`

2024-05-24 10:22 UTC, ludoboludo requested changes

2024-05-24 10:22 UTC, ludoboludo commented on sections/main-product.liquid
> +</product-info>
This is somehow breaking the padding applied and the content is flush with the header at the top: 
![](https://screenshot.click/24-07-pnum5-zx2mq.png)

Seems like it's missing a `display: block;` that it was getting from the user agent stylesheet: 
![](https://screenshot.click/24-11-ymvtp-xtpm3.png)

2024-05-24 10:22 UTC, ludoboludo commented on sections/main-product.liquid
> +</product-info>
Which should also fix the color scheme issue not working atm: 
![](https://screenshot.click/24-02-r0jh7-a3n9u.png)

2024-05-28 18:19 UTC, merged