Show bundle components on the cart page
Shopify/dawn pull request #3478
Opened 2024-05-15 19:46 UTC by mironov

### PR Summary: 

Show bundle components on the cart page

### Why are these changes introduced?

Fixes #3477

### What approach did you take?

Render `item.item_components` if they are present.

### Other considerations

n/a

### Decision log

n/a

### Visual impact on existing themes

Enhance user experience for bundles.

### Testing steps/scenarios

- Add a regular product to cart and confirm no components are rendered
- Add a bundled product to cart and confirm that its components are rendered

### Demo links

https://github.com/Shopify/dawn/assets/20403/b1f9f0b4-05cf-45dd-b4db-7b4dce90c6d6

### Checklist
- [x] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2025-01-24 19:40 UTC, ludoboludo requested changes
Other than the HTML tag used looks good. 
Thanks for the PR 👍

2025-01-24 19:40 UTC, ludoboludo commented on sections/main-cart-items.liquid
> +                        </sub>
I wonder if this is the right element for the job. Id go with an unordered list instead maybe.

When i look at the sub element in docs, MDN for example, it does mention using them in specific scenarios: 
>should be displayed as subscript for solely typographical reasons

2025-01-28 14:41 UTC, ludoboludo commented on sections/main-cart-items.liquid
> +                        <ul>
I think that way is good unless bullet points are nice but yeah that `padding-inline-start` seems a little much

2025-02-05 18:09 UTC, carrotderek commented
Hi @mironov, thanks for creating this PR 🙏🏼!

At this moment, we're considering how to best represent and handle components within the theme. Since the area is under evaluation and may undergo changes, we believe it's prudent to hold off on merging new changes related to this functionality. 

Again, thanks for your contribution. We really appreciate the time and effort invested and encourage you to stay involved once we've solidified our plans.

2025-02-06 03:29 UTC, mironov commented
@carrotderek That's great to hear! I'm really excited that the team is actively exploring ways to improve how bundles are displayed in the Dawn theme.

We found that bundles created with cart transform functions often run into minor quirks in the native Shopify themes, particularly with how they're displayed on collection pages or in the cart. I'd love to share some of our findings if that might help inform future improvements. Let me know if there's any way I can assist.

2025-07-08 14:20 UTC, closed without merging