Use translation keys for default values in liquid files
Shopify/dawn pull request #3484
Opened 2024-05-22 14:53 UTC by dpasiliao

### PR Summary: 

Use translation keys as default values for sections

### Why are these changes introduced?
This updates Dawn to make use of the new update that allows default content to be translated and rendered. 

### What approach did you take?
Manually updated all the default values in the liquid schemas with translation keys and moved those values to the `en.default.schema.json` 

### Other considerations

### Decision log

| # | Decision | Alternatives | Rationale | Downsides |
|---|---|---|---|---|
| 1 |   |   |   |   |

### Visual impact on existing themes

Any default value when a merchant adds a new section in the theme editor will now match the default language of their store

### Testing steps/scenarios

- [ ] While waiting for translations to arrive, add each section from the theme into your store and make sure that the strings that appear in the section are not translation keys (i.e. `t:some.translation.key`)
- [ ] Once translations arrive, change your store's default language to a language is not English and has available translations
- [ ] Add a new section and check if the values of the section match the language you've set your store's default language to

### Demo links

- [Store](https://19b2dc.myshopify.com/?preview_theme_id=136547795095)
- [Editor](https://19b2dc.myshopify.com/admin/themes/136547795095/editor)

### Checklist
- [x] Added PR summary for [release notes](https://themes.shopify.com/themes/dawn/styles/default#ReleaseNotes)
- [ ] Requested review from UX (Only for changes that are affecting the experience or perceivable visual details)
- [ ] Created a ticket for the [help.shopify.com](https://help.shopify.com) documentation team about updates to theme settings. (Internal-only task)
- [x] Followed [theme code principles](https://github.com/Shopify/dawn/blob/main/.github/CONTRIBUTING.md#theme-code-principles)
- [x] Linted with [Theme Check](https://github.com/Shopify/theme-check)
- [x] Tested on [mobile](https://shopify.dev/themes/store/requirements#mobile-browser-requirements)
- [x] Tested on [multiple browsers](https://shopify.dev/themes/store/requirements#desktop-browser-requirements)
- [x] Tested for [accessibility](https://shopify.dev/themes/best-practices/accessibility)

2024-05-24 13:34 UTC, dan-menard requested changes

2024-05-24 13:34 UTC, dan-menard commented on locales/en.default.schema.json
> +              "default": "<p>Share contact information, store details, and brand content with your customers.</p>"
It's generally an antipattern to put HTML in translation files. This has burned me before a few times, like when a mobile native app reuses our locale files, or translators mis-interpreting what the HTML is doing.

Why do we need to do it here?

2024-05-24 13:34 UTC, dan-menard commented on sections/email-signup-banner.liquid
> +          "default": "t:sections.email-signup-banner.blocks.paragraph.settings.paragraph.default",
Ah yeah, related to my previous comment, we should keep the `<p>` tags here in the liquid file, rather than the translations.

2024-05-24 16:13 UTC, dan-menard approved these changes

2024-05-29 20:16 UTC, Al-Campuzano approved these changes
LGTM :)

2024-05-29 20:18 UTC, merged